export const images = [
    {
      src: "/images/purple_clouds.png",
      title: "Purple Clouds",
      description: '20"x 20" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/digital_planet.png",
      title: "Digital Planet",
      description: '36"x 2" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/gold_poppies.png",
      title: "Gold Poppies",
      description: '20"x 20" Acrylic on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/woman_figure.png",
      title: "Poppy",
      description: '20"x 16" Oil and Acrylic on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/mothers_love.png",
      title: "A Mother's Love",
      description: '54"x 48" Oil and Acrylic on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/space_winds.png",
      title: "Space Winds",
      description: '36"x 48" Oil and Acrylic on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/black_orchid.png",
      title: "Black Orchid",
      description: '36"x 48" Acrylic on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/moon_islands.png",
      title: "Moon Islands",
      description: '24"x 96" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/sun_islands.png",
      title: "Sun Islands",
      description: '16"x 20" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/ocean_breeze.png",
      title: "Ocean Breeze",
      description: '12"x 24" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/deadpool_1.png",
      title: "Deadpool Commission",
      description: '14"x 20" Oil on canvas',
      width: 400,
      height: 400,
    },
    {
      src: "/images/mural_1.png",
      title: "Mural Commission",
      description: 'Mixed Medium Mural on Ceiling',
      width: 400,
      height: 400,
    },
    {
      src: "/images/rose_watercolor.png",
      title: "Rose",
      description: '8"x 10" Watercolor',
      width: 400,
      height: 400,
    },
    {
      src: "/images/bird_gold.png",
      title: "Bird with Poppies",
      description: '8"x 10" Mixed Medium',
      width: 400,
      height: 400,
    },
    {
      src: "/images/possum_watercolor.png",
      title: "Opossum",
      description: '8"x 10" Watercolor',
      width: 400,
      height: 400,
    },
    {
      src: "/images/frog_watercolor.png",
      title: "Frog",
      description: '8"x 10" Watercolor',
      width: 400,
      height: 400,
    },
    {
      src: "/images/moon_ghosts.png",
      title: "Moon Ghosts",
      description: '8"x 10" Illustration',
      width: 400,
      height: 400,
    },
    {
      src: "/images/dali_cat.png",
      title: "Dali Cat",
      description: '8"x 10" Illustration',
      width: 400,
      height: 400,
    },
    {
      src: "/images/raven.png",
      title: "Raven",
      description: '8"x 10" Illustration',
      width: 400,
      height: 400,
    },
    // Add more images as needed
  ];
  